# Generated by Django 5.1.1 on 2024-09-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='info_sources/')),
                ('category', models.CharField(choices=[('blog', 'Blog'), ('website', 'Website'), ('news_portal', 'News Portal'), ('youtube', 'YouTube Channel'), ('other', 'Other')], max_length=20)),
                ('tags', models.CharField(help_text='Comma-separated tags', max_length=255)),
            ],
        ),
    ]
