# Generated by Django 5.1.1 on 2024-09-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('category', models.CharField(choices=[('blog', 'Blog'), ('website', 'Website'), ('news_channels', 'News Channels'), ('youtube', 'YouTube'), ('redits', 'Redits'), ('facebook', 'Facebook'), ('other', 'Other')], max_length=20)),
                ('tags', models.CharField(help_text='Comma-separated tags', max_length=255)),
                ('prompts', models.TextField(blank=True, help_text='Textual prompts or descriptions', null=True)),
                ('rating', models.DecimalField(choices=[(1.0, '1 Star'), (1.5, '1.5 Stars'), (2.0, '2 Stars'), (2.5, '2.5 Stars'), (3.0, '3 Stars'), (3.5, '3.5 Stars'), (4.0, '4 Stars'), (4.5, '4.5 Stars'), (5.0, '5 Stars')], decimal_places=1, default=1.0, help_text='Rating from 1 to 5 stars', max_digits=3)),
                ('subscribers_count', models.CharField(help_text='Number of subscribers', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
            ],
        ),
    ]
